// <auto-generated />
using System;
using GameDeals.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameDeals.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250602071040_AddOperacoesLog")]
    partial class AddOperacoesLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GameDeals.API.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ComentarioTexto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("comentario_texto");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataComentario")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_comentario");

                    b.Property<int>("IdPromocao")
                        .HasColumnType("int")
                        .HasColumnName("id_promocao");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<bool>("IsDono")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isDono");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdPromocao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("GameDeals.API.Models.OperacaoLogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("acao");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Detalhes")
                        .HasColumnType("longtext")
                        .HasColumnName("detalhes");

                    b.Property<string>("EntidadeAfetada")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entidade_afetada");

                    b.Property<int?>("IdEntidade")
                        .HasColumnType("int")
                        .HasColumnName("id_entidade");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("OperacoesLog");
                });

            modelBuilder.Entity("GameDeals.API.Models.Promocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Cupom")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("imagem_url");

                    b.Property<string>("MotivoInativacao")
                        .HasColumnType("longtext")
                        .HasColumnName("motivo_inativacao");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("StatusPublicacao")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status_publicacao");

                    b.Property<TimeSpan?>("TempoPostado")
                        .HasColumnType("time(6)")
                        .HasColumnName("tempo_postado");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Promocoes");
                });

            modelBuilder.Entity("GameDeals.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Contribuicoes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EstaBloqueado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NomeSobrenome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GameDeals.Models.Curtidas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("id_promocao")
                        .HasColumnType("int")
                        .HasColumnName("id_promocao");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("id");

                    b.HasIndex("id_promocao");

                    b.HasIndex("id_usuario");

                    b.ToTable("Curtidas");
                });

            modelBuilder.Entity("GameDeals.API.Models.Comentario", b =>
                {
                    b.HasOne("GameDeals.API.Models.Promocao", "Promocao")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdPromocao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDeals.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Promocao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameDeals.API.Models.OperacaoLogModel", b =>
                {
                    b.HasOne("GameDeals.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameDeals.API.Models.Promocao", b =>
                {
                    b.HasOne("GameDeals.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameDeals.Models.Curtidas", b =>
                {
                    b.HasOne("GameDeals.API.Models.Promocao", "Promocao")
                        .WithMany()
                        .HasForeignKey("id_promocao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDeals.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promocao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GameDeals.API.Models.Promocao", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
